# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"%\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"A\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x19\n\x04vote\x18\x02 \x01(\x0e\x32\x0b.twopc.Vote\"R\n\x0f\x44\x65\x63isionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\'\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x15.twopc.GlobalDecision\"7\n\x10\x44\x65\x63isionResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\"6\n\rVotingResults\x12%\n\x06result\x18\x01 \x01(\x0e\x32\x15.twopc.GlobalDecision*=\n\x04Vote\x12\x14\n\x10VOTE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bVOTE_COMMIT\x10\x01\x12\x0e\n\nVOTE_ABORT\x10\x02*S\n\x0eGlobalDecision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44\x45\x43ISION_COMMIT\x10\x01\x12\x12\n\x0e\x44\x45\x43ISION_ABORT\x10\x02\x32\xbc\x01\n\x0eTwoPhaseCommit\x12\x33\n\x08SendVote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponse\x12?\n\x0cSendDecision\x12\x16.twopc.DecisionRequest\x1a\x17.twopc.DecisionResponse\x12\x34\n\tQueryVote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTE']._serialized_start=325
  _globals['_VOTE']._serialized_end=386
  _globals['_GLOBALDECISION']._serialized_start=388
  _globals['_GLOBALDECISION']._serialized_end=471
  _globals['_VOTEREQUEST']._serialized_start=22
  _globals['_VOTEREQUEST']._serialized_end=59
  _globals['_VOTERESPONSE']._serialized_start=61
  _globals['_VOTERESPONSE']._serialized_end=126
  _globals['_DECISIONREQUEST']._serialized_start=128
  _globals['_DECISIONREQUEST']._serialized_end=210
  _globals['_DECISIONRESPONSE']._serialized_start=212
  _globals['_DECISIONRESPONSE']._serialized_end=267
  _globals['_VOTINGRESULTS']._serialized_start=269
  _globals['_VOTINGRESULTS']._serialized_end=323
  _globals['_TWOPHASECOMMIT']._serialized_start=474
  _globals['_TWOPHASECOMMIT']._serialized_end=662
# @@protoc_insertion_point(module_scope)
