# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import twopc_pb2 as twopc__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in twopc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPhaseCommitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendVote = channel.unary_unary(
                '/twopc.TwoPhaseCommit/SendVote',
                request_serializer=twopc__pb2.VoteRequest.SerializeToString,
                response_deserializer=twopc__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.SendDecision = channel.unary_unary(
                '/twopc.TwoPhaseCommit/SendDecision',
                request_serializer=twopc__pb2.DecisionRequest.SerializeToString,
                response_deserializer=twopc__pb2.DecisionResponse.FromString,
                _registered_method=True)
        self.QueryVote = channel.unary_unary(
                '/twopc.TwoPhaseCommit/QueryVote',
                request_serializer=twopc__pb2.VoteRequest.SerializeToString,
                response_deserializer=twopc__pb2.VoteResponse.FromString,
                _registered_method=True)


class TwoPhaseCommitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendVote(self, request, context):
        """vote-phase messaging loop - for coordinator use
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDecision(self, request, context):
        """decision-phase messaging loop - for coordinator use
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryVote(self, request, context):
        """decision-phase info helper - retrieve votes from phase 1 to count and avoid re-voting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPhaseCommitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendVote': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVote,
                    request_deserializer=twopc__pb2.VoteRequest.FromString,
                    response_serializer=twopc__pb2.VoteResponse.SerializeToString,
            ),
            'SendDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDecision,
                    request_deserializer=twopc__pb2.DecisionRequest.FromString,
                    response_serializer=twopc__pb2.DecisionResponse.SerializeToString,
            ),
            'QueryVote': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryVote,
                    request_deserializer=twopc__pb2.VoteRequest.FromString,
                    response_serializer=twopc__pb2.VoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPhaseCommit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.TwoPhaseCommit', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPhaseCommit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseCommit/SendVote',
            twopc__pb2.VoteRequest.SerializeToString,
            twopc__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseCommit/SendDecision',
            twopc__pb2.DecisionRequest.SerializeToString,
            twopc__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseCommit/QueryVote',
            twopc__pb2.VoteRequest.SerializeToString,
            twopc__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
